### PR TITLE
Fix DB2ZJdbcTemplate ClassCastExecption

### PR DESCRIPTION
**Pull request by Barry-RG**

### CODE REVIEW

**Comment by Barry-RG** [comment]
Thanks for pointing out the ClassCastException @gahoekstraibm 
An oversight on my part

**Comment by gahoekstraibm** [comment]
Thanks a lot, @Barry-RG. I will test it soon. 
I do have some doubt whether it would not be better to just add the method for callable statements to the core JdbcTemplate, as it is not really DB2Z specific and could be helpful for other database plugins as well. But that is up to you in the end...

**Comment by gahoekstraibm** [comment]
@Barry-RG With the latest commit, the DB2Z plugin works as expected. Could you please check my previous comment as well?

**Comment by Barry-RG** [comment]
Thanks @gahoekstraibm 
We are in two minds about the callable statement being part of core jdbctemplate. You are correct that this will probably be useful for other database plugins but we do not have a use case right now. I am going to put some research time aside to help with a decision.

**Pull request merged**
